# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Corporate-House-Management' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Corporate-House-Management
	pod 'Alamofire', '~> 5.5'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'Firebase/Database'
  pod 'Firebase/Core'

  target 'Corporate-House-ManagementTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Corporate-House-ManagementUITests' do
    # Pods for testing
  end

end
